#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Read scripts/apps.json and answer questions about it.

One file names the applications the demo is built from and what each one is
supposed to print. Three things need that list and used to disagree about it:
the staging script, the page's menu, and CI's assertions. They all come
through here now.

Subcommands:
  list        one "<name>\\t<app path>" per line, for the staging script
  manifest    the JSON the page and the site checker read
  score       the count of unmodified upstream samples, which is the measure
              ROADMAP.md sets. Upstream test suites are evidence for the port
              and are deliberately not counted.
"""
import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
APPS = HERE / "apps.json"


def score(builds: list[dict]) -> int:
    """Upstream samples that run unmodified. See ROADMAP.md."""
    return sum(1 for b in builds if b.get("upstream") and b.get("kind") == "sample")


def load(module: str) -> list[dict]:
    builds = json.loads(APPS.read_text())["builds"]
    for b in builds:
        b["app"] = b["app"].replace("{module}", module)
    return builds


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--module", default=str(HERE.parent),
                    help="this repository, substituted for {module} in an app path")
    ap.add_argument("command", choices=("list", "manifest", "score"))
    args = ap.parse_args()

    builds = load(args.module)

    if args.command == "list":
        for b in builds:
            print(f"{b['name']}\t{b['app']}")
        return 0

    if args.command == "score":
        print(score(builds))
        return 0

    # The manifest is the apps list with the module path resolved and the
    # published location of each module filled in. Deliberately the same
    # shape, so that adding a field to apps.json makes it available to the
    # page without a second edit here.
    out = {
        "_comment": "Generated by scripts/stage_site.sh from scripts/apps.json. Do not edit.",
        "score": score(builds),
        "builds": [dict(b, path=f"m/{b['name']}.wasm") for b in builds],
    }
    json.dump(out, sys.stdout, indent=2)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
