#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Produce zephyr/offsets.h for the wasm arch.

Zephyr's own scripts/build/gen_offset_header.py reads SHN_ABS symbols out of an
ELF object. Wasm has no absolute symbols at all: the ELF trick that Zephyr uses,
an inline-asm `.equ`, makes the LLVM wasm backend fail outright with
"absolute addressing not supported".

So on wasm each offset is emitted as a real constant in a data section named
z_offsets (see the CONFIG_WASM branch of GEN_ABSOLUTE_SYM). The value is then
read back out of the compiler's own assembly output, where every constant
appears as a label followed by a .int32/.int64 directive:

    __k_thread_t_b_OFFSET:
            .int32  4

Reading the assembly rather than the object keeps this to one regex over text
that the compiler is contractually required to emit, instead of scraping two
different wasm-objdump reports or writing a wasm binary parser.

Struct layout must come from the target compiler: wasm32 packs these
differently from the host, so compiling offsets.c natively would give wrong
answers.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# A label line, then (skipping comments/directives we do not care about) the
# directive carrying the value. Clang mangles function-scope statics as
# "<func>.<name>", which is how they arrive when kernel_offsets.h wraps
# everything in GEN_ABS_SYM_BEGIN, so the optional prefix is stripped.
LABEL_RE = re.compile(r"^(?P<label>[A-Za-z_.$][\w.$]*):\s*$")
VALUE_RE = re.compile(r"^\s*\.(?P<width>int8|int16|int32|int64|quad|long|zero)\s+(?P<value>-?\d+)")
WANTED_SUFFIXES = ("_OFFSET", "_SIZEOF")


def compile_to_asm(compiler: str, source: Path, flags: list[str], out: Path) -> None:
    cmd = [compiler, "-S", "-o", str(out), str(source), *flags]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(f"gen_offsets_wasm: compile failed\n  {' '.join(cmd)}\n{proc.stderr}")
        raise SystemExit(proc.returncode)


def parse_asm(asm: str) -> dict[str, int]:
    """Map every *_OFFSET / *_SIZEOF label to the integer that follows it."""
    offsets: dict[str, int] = {}
    pending: str | None = None
    for line in asm.splitlines():
        label = LABEL_RE.match(line)
        if label:
            name = label.group("label").split(".")[-1]
            pending = name if name.endswith(WANTED_SUFFIXES) else None
            continue
        if pending is None:
            continue
        value = VALUE_RE.match(line)
        if value:
            # .zero N means N zero bytes, i.e. the constant is 0.
            offsets[pending] = 0 if value.group("width") == "zero" else int(value.group("value"))
            pending = None
        elif line.strip() and not line.lstrip().startswith(("#", ".size", ".type", ".hidden", ".globl", ".section")):
            pending = None
    return offsets


def render(offsets: dict[str, int]) -> str:
    lines = [
        "/* Generated by scripts/gen_offsets_wasm.py. Do not edit. */",
        "",
        "#ifndef ZEPHYR_GENERATED_OFFSETS_H",
        "#define ZEPHYR_GENERATED_OFFSETS_H",
        "",
    ]
    for name in sorted(offsets):
        lines.append(f"#define {name} 0x{offsets[name]:x}")
    lines += ["", "#endif /* ZEPHYR_GENERATED_OFFSETS_H */", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-i", "--input", required=True, type=Path,
                    help="offsets.c, or a .s already produced from it")
    ap.add_argument("-o", "--output", required=True, type=Path)
    ap.add_argument("--compiler", help="compiler to run when input is a .c file")
    ap.add_argument("--flag", action="append", default=[], dest="flags",
                    help="compiler flag, repeatable")
    ap.add_argument("--rsp", type=Path,
                    help="file of compiler flags, one per line; the build writes "
                         "this because the real flags are only known at generate time")
    args = ap.parse_args()

    if args.rsp and args.rsp.exists():
        for line in args.rsp.read_text().splitlines():
            line = line.strip()
            # A bare -I/-D/-isystem with nothing after it is an empty
            # property, not a flag.
            if line and line not in ("-I", "-D", "-isystem"):
                args.flags.append(line)

    if args.input.suffix == ".c":
        if not args.compiler:
            ap.error("--compiler is required when the input is a .c file")
        asm_path = args.output.with_suffix(".s")
        asm_path.parent.mkdir(parents=True, exist_ok=True)
        compile_to_asm(args.compiler, args.input, args.flags, asm_path)
    else:
        asm_path = args.input

    offsets = parse_asm(asm_path.read_text())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(offsets))
    print(f"gen_offsets_wasm: {len(offsets)} constants -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
